name: 'Check vulnerable NuGet packages'
author: 'elmah.io'
description: 'GitHub Action to check for vulnerable NuGet packages.'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  projects:
    description: |
      A newline-separated list of project or solution files to operate on.
      If not specified, the command will search the current directory for one.
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.projects }}
