name: 'Check vulnerable NuGet packages'
author: 'elmah.io'
description: 'GitHub Action to check for vulnerable NuGet packages.'
branding:
  icon: 'check-circle'
  color: 'green'
runs:
  using: 'docker'
  image: 'Dockerfile'